"""
LangGraph node implementations for BakeSquad (Phase 2).

Each function takes BakeSquadState and returns a partial-state dict that
LangGraph merges into the running state.  Nodes call the same underlying
modules that main.py uses — no business logic is duplicated here.

Node inventory:
  classify_intent  — route turn type (new_search | re_filter | re_search | factual)
  expand_query     — Step 1: QueryPlan via LLM
  clarify          — pause graph and ask user a clarifying question
  search           — Steps 2–5: DuckDuckGo + snippet scoring + adaptive retry
  fetch            — Step 6: parallel page fetch
  parse            — Step 7: parallel LLM recipe parsing
  verify           — Step 7b: majority-vote category reconciliation
  score            — Steps 8–10: ratios + technique scoring + LLM explanations
  filter_node      — re_filter: ingredient/fat-type constraint on existing results
  factual          — return the direct_answer generated by classify_intent
  memory           — persist ratio cache, liked recipes, update user prefs
"""

from __future__ import annotations

import logging
from collections import Counter
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from bakesquad.graph.state import BakeSquadState

logger = logging.getLogger(__name__)

_CLARIFY_THRESHOLD = 0.55


# ---------------------------------------------------------------------------
# classify_intent
# ---------------------------------------------------------------------------

def classify_intent(state: BakeSquadState) -> dict:
    """
    Classify the incoming user turn and extract any filter/search parameters.

    First turn (no query_plan yet) → always new_search, no LLM call.
    Follow-up turns → 1 LLM call via classify_turn(), which also generates
    direct_answer for factual turns in the same response.
    """
    from bakesquad.session import classify_turn

    if state.get("query_plan") is None:
        return {"turn_type": "new_search"}

    session = _state_to_session(state)
    refine = classify_turn(session, state["user_query"])
    turn_type = refine.get("turn_type", "factual")

    update: dict = {"turn_type": turn_type}
    if turn_type == "re_filter":
        update["exclude_ingredients"] = [
            e.strip() for e in (refine.get("exclude_ingredients") or []) if e.strip()
        ]
        update["require_fat_type"] = refine.get("require_fat_type")
    elif turn_type == "factual":
        update["factual_answer"] = refine.get("direct_answer")
    elif turn_type == "re_search":
        # Carry the LLM-generated updated_query forward for expand_query to use
        updated_q = refine.get("updated_query")
        if updated_q:
            update["user_query"] = updated_q

    return update


# ---------------------------------------------------------------------------
# expand_query  (Step 1)
# ---------------------------------------------------------------------------

def expand_query(state: BakeSquadState) -> dict:
    """
    Step 1: build QueryPlan from the user query via LLM.

    For re_search turns, seeds the query with the previous category + merged
    constraints so the LLM doesn't re-derive them from scratch.

    category_confidence is set to 1.0 — the hard Literal schema forces a
    committed answer.  Phase 3 will add soft classification (category_scores)
    and lower this when the model is uncertain.
    """
    from bakesquad.search.ingestion import IngestionPipeline

    pipeline = IngestionPipeline(trusted_sources=[])
    recency = state.get("recency")
    query = state["user_query"]

    # For re-search, prefix with prior context so query understanding is guided
    prior_plan = state.get("query_plan")
    if prior_plan is not None and state.get("turn_type") == "re_search":
        query = (
            f"[Context: continuing from previous search. "
            f"Category={prior_plan.category}. "
            f"Active constraints: {'; '.join(prior_plan.hard_constraints)}. "
            f"New request: {query}]"
        )

    plan = pipeline._build_query_plan(query, recency)
    update: dict = {
        "query_plan": plan,
        "category_confidence": plan.confidence,
        "category_override": None,   # clear any previous override on a fresh search
        "search_retry_count": 0,
        "messages": [
            {"role": "assistant",
             "content": f"[Step 1] Category: {plan.category} (confidence: {plan.confidence:.2f})"}
        ],
    }
    if plan.clarification_question:
        update["clarify_question"] = plan.clarification_question
    return update


# ---------------------------------------------------------------------------
# clarify
# ---------------------------------------------------------------------------

def clarify(state: BakeSquadState) -> dict:
    """
    Pause the graph and surface a clarifying question to the user.

    Uses langgraph.types.interrupt() — execution suspends here and resumes
    when the caller injects the user's answer via graph.invoke() with the
    same thread_id.  The answer becomes the new user_query on the next turn,
    which classify_intent routes back to expand_query.
    """
    try:
        from langgraph.types import interrupt
    except ImportError:
        logger.warning("langgraph not installed; clarify node will not pause")
        return {}

    question = (
        state.get("clarify_question")
        or "Could you tell me more about what you're looking for? "
           "(e.g. is this a bread, cake, or cookie?)"
    )
    interrupt(question)
    return {"clarify_question": None}


# ---------------------------------------------------------------------------
# search  (Steps 2–5)
# ---------------------------------------------------------------------------

def search(state: BakeSquadState) -> dict:
    """Steps 2–5: DuckDuckGo search, snippet relevance scoring, domain cap, adaptive retry."""
    from bakesquad.search.ingestion import IngestionPipeline

    plan = state["query_plan"]
    pipeline = IngestionPipeline(trusted_sources=[])
    recency = state.get("recency")

    candidates = pipeline._search_and_filter(
        state["user_query"], plan.queries, recency
    )
    return {
        "snippets": candidates,
        "messages": [
            {"role": "assistant",
             "content": f"[Step 2-5] {len(candidates)} candidates found"}
        ],
    }


# ---------------------------------------------------------------------------
# fetch  (Step 6)
# ---------------------------------------------------------------------------

def fetch(state: BakeSquadState) -> dict:
    """Step 6: parallel HTTP fetch + BeautifulSoup extraction."""
    from bakesquad.search.ingestion import IngestionPipeline

    pipeline = IngestionPipeline(trusted_sources=[])
    pages = pipeline._fetch_pages(state["snippets"])
    return {
        "fetched_pages": pages,
        "messages": [
            {"role": "assistant",
             "content": f"[Step 6] {len(pages)} pages fetched"}
        ],
    }


# ---------------------------------------------------------------------------
# parse  (Step 7)
# ---------------------------------------------------------------------------

def parse(state: BakeSquadState) -> dict:
    """Step 7: parallel LLM extraction of structured recipes (+ technique_signals/notes)."""
    from bakesquad.parser import parse_recipes_parallel

    recipes = parse_recipes_parallel(state["fetched_pages"])
    return {
        "parsed_recipes": recipes,
        "messages": [
            {"role": "assistant",
             "content": f"[Step 7] {len(recipes)} recipes parsed"}
        ],
    }


# ---------------------------------------------------------------------------
# verify  (Step 7b — category reconciliation)
# ---------------------------------------------------------------------------

def verify(state: BakeSquadState) -> dict:
    """
    Majority-vote the Step 7 parsed categories against Step 1.

    If the dominant category from parsed recipes differs from query_plan.category,
    set category_override.  The score node reads category_override before
    query_plan.category for all ratio range lookups and scoring.

    Caps correction at one retry (search_retry_count) to prevent infinite loops.
    """
    recipes = state.get("parsed_recipes") or []
    step7_cats = Counter(
        r.category for r in recipes
        if getattr(r, "category", None) and r.category != "other" and not r.parse_error
    )

    if not step7_cats:
        return {"category_override": None}

    dominant, count = step7_cats.most_common(1)[0]
    plan_category = getattr(state.get("query_plan"), "category", None)

    if dominant != plan_category and count >= len(recipes) / 2:
        logger.warning("verify: category override %s → %s", plan_category, dominant)
        return {"category_override": dominant}

    return {"category_override": None}


# ---------------------------------------------------------------------------
# score  (Steps 8–10)
# ---------------------------------------------------------------------------

def score(state: BakeSquadState) -> dict:
    """
    Steps 8–10: normalization, ratio engine, scoring, LLM explanations.

    After scoring live web results, recalls semantically similar recipes from the
    personal corpus (stored via the memory node on previous runs) and merges them
    into the result set. Recalled recipes use cached ratios and are re-scored
    against the current query plan so weights and boosts are applied fresh.

    Applies category_override if verify set one; otherwise uses query_plan.category.
    """
    from bakesquad.memory import embed_text, get_liked_recipes, get_semantic_candidates
    from bakesquad.models import ParsedRecipe, RatioResult
    from bakesquad.ratio_engine import compute_ratios
    from bakesquad.scorer import add_explanations, score_all

    recipes = state.get("parsed_recipes") or []
    plan = state["query_plan"]
    if state.get("category_override"):
        plan = plan.model_copy(update={"category": state["category_override"]})
    user_prefs = state.get("user_prefs") or {}

    # ── Recall from corpus ────────────────────────────────────────────────
    # Embed the query and fetch the top-3 stored recipes most similar to it.
    # Skip any URL already in the live result set to avoid duplicates.
    live_urls = {r.url for r in recipes}
    recalled_recipes: list[ParsedRecipe] = []
    recalled_ratios: list[RatioResult] = []
    try:
        query_text = f"{state['user_query']} {plan.category}"
        query_emb = embed_text(query_text)
        candidates = get_semantic_candidates(
            query_emb, top_k=3, category_filter=plan.category
        )
        # Load full ScoredRecipe data from liked_recipes for high-similarity matches
        if candidates:
            liked_map = {
                row["url"]: row
                for row in get_liked_recipes()
            }
            import json as _json
            for c in candidates:
                if c["similarity"] < 0.30 or c["url"] in live_urls:
                    continue
                row = liked_map.get(c["url"])
                if not row:
                    continue
                try:
                    stored = _json.loads(row["recipe_json"])
                    r = ParsedRecipe(**stored["recipe"])
                    rt = RatioResult(**stored["ratios"])
                    recalled_recipes.append(r)
                    recalled_ratios.append(rt)
                    live_urls.add(c["url"])
                except Exception as exc:
                    logger.debug("recall: skipping %s — %s", c["url"], exc)
    except Exception as exc:
        logger.warning("score: corpus recall failed: %s", exc)

    # ── Score live + recalled together ───────────────────────────────────
    if not recipes and not recalled_recipes:
        return {"scored_recipes": [], "ratio_results": []}

    all_recipes = recipes + recalled_recipes
    # For live recipes compute ratios fresh; recalled recipes use their stored ratios
    live_ratios = [compute_ratios(r) for r in recipes]
    all_ratios = live_ratios + recalled_ratios

    scored = score_all(all_recipes, all_ratios, plan, user_prefs)
    add_explanations(scored)

    top = scored[0].recipe.title if scored else "none"
    recalled_count = len(recalled_recipes)
    return {
        "ratio_results": all_ratios,
        "scored_recipes": scored,
        "messages": [
            {"role": "assistant",
             "content": (
                 f"[Step 10] {len(scored)} recipes scored"
                 + (f" ({recalled_count} from corpus)" if recalled_count else "")
                 + f". Top: {top}"
             )}
        ],
    }


# ---------------------------------------------------------------------------
# filter_node  (re_filter — zero LLM calls)
# ---------------------------------------------------------------------------

def filter_node(state: BakeSquadState) -> dict:
    """
    Apply ingredient exclusions and fat-type constraint to the current scored results.

    Operates directly on state fields — no ConversationSession bridge needed.
    Returns the filtered + re-ranked scored_recipes list.
    If nothing passes the filter, sets turn_type=re_search so the graph falls
    back to a full new search with the constraints carried forward.
    """
    recipes = state.get("parsed_recipes") or []
    ratios = state.get("ratio_results") or []
    scored = state.get("scored_recipes") or []
    exclude = [e.lower().strip() for e in (state.get("exclude_ingredients") or []) if e.strip()]
    require_fat = state.get("require_fat_type")

    passing = []
    for recipe, ratio, scored_recipe in zip(recipes, ratios, scored):
        ok = True
        if exclude:
            for term in exclude:
                if any(term in ing.name.lower() for ing in recipe.ingredients):
                    ok = False
                    break
        if ok and require_fat and ratio.fat_type != require_fat:
            ok = False
        if ok:
            passing.append((recipe, ratio, scored_recipe))

    if not passing:
        # Nothing passes — escalate to a new search with the constraints
        logger.info("filter_node: no results passed filter; escalating to re_search")
        return {"turn_type": "re_search", "scored_recipes": []}

    # Re-rank by existing composite score (scores themselves don't change)
    passing.sort(key=lambda t: t[2].composite_score, reverse=True)
    filtered_scored = []
    for rank, (_, _, s) in enumerate(passing, 1):
        s.rank = rank
        filtered_scored.append(s)

    filtered_recipes = [t[0] for t in passing]
    filtered_ratios  = [t[1] for t in passing]

    return {
        "parsed_recipes": filtered_recipes,
        "ratio_results":  filtered_ratios,
        "scored_recipes": filtered_scored,
        "messages": [
            {"role": "assistant",
             "content": f"[re_filter] {len(filtered_scored)} recipes pass filter"}
        ],
    }


# ---------------------------------------------------------------------------
# factual
# ---------------------------------------------------------------------------

def factual(state: BakeSquadState) -> dict:
    """Return the direct_answer set by classify_intent (no additional LLM call)."""
    answer = state.get("factual_answer") or "I'm not sure about that."
    return {
        "messages": [{"role": "assistant", "content": answer}],
    }


# ---------------------------------------------------------------------------
# memory
# ---------------------------------------------------------------------------

def memory(state: BakeSquadState) -> dict:
    """
    Write-through memory operations after each scored turn:

    1. Upsert ratio_cache for every scored recipe URL.
    2. Save recipe embeddings for every successfully scored recipe (enables
       semantic recall on future queries).
    3. Update user_prefs from feedback history if use_feedback_prefs is True.
    4. Pre-load liked_recipe_urls for fast filtering on future turns.

    Recipe liking (save_liked_recipe) is triggered by explicit user feedback
    via the /feedback API endpoint, not automatically here.
    """
    from bakesquad.memory import (
        cache_put,
        embed_text,
        get_liked_urls,
        load_prefs,
        save_embedding,
        save_prefs,
        update_user_prefs_from_feedback,
    )

    scored = state.get("scored_recipes") or []
    ratios = state.get("ratio_results") or []

    # 1. Upsert ratio cache
    for ratio in ratios:
        try:
            cache_put(ratio.url, ratio.category, ratio.model_dump())
        except Exception as exc:
            logger.warning("memory: cache_put failed for %s: %s", ratio.url, exc)

    # 2. Save embeddings — title + category + ingredient names as embedding text
    for s in scored:
        try:
            ing_names = " ".join(i.name for i in (s.recipe.ingredients or []))
            text = f"{s.recipe.title} {s.recipe.category} {ing_names}"
            embedding = embed_text(text)
            save_embedding(s.recipe.url, s.recipe.title, s.recipe.category, embedding)
        except Exception as exc:
            logger.warning("memory: save_embedding failed for %s: %s", s.recipe.url, exc)

    # 3. Refresh user_prefs from feedback history
    try:
        updated_prefs = update_user_prefs_from_feedback()
        save_prefs(updated_prefs)
    except Exception as exc:
        logger.warning("memory: pref inference failed: %s", exc)
        updated_prefs = load_prefs()

    # 4. Refresh liked URLs
    try:
        liked_urls = get_liked_urls()
    except Exception as exc:
        logger.warning("memory: get_liked_urls failed: %s", exc)
        liked_urls = list(state.get("liked_recipe_urls") or [])

    return {
        "user_prefs": updated_prefs,
        "liked_recipe_urls": liked_urls,
    }


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _state_to_session(state: BakeSquadState):
    """
    Build a minimal ConversationSession from graph state for legacy callers
    (classify_intent uses session.classify_turn which expects a session object).
    Removed in Phase 3 when session.py is replaced by graph state entirely.
    """
    from bakesquad.session import ConversationSession

    session = ConversationSession(original_query=state.get("user_query", ""))
    plan    = state.get("query_plan")
    recipes = state.get("parsed_recipes") or []
    ratios  = state.get("ratio_results") or []
    scored  = state.get("scored_recipes") or []

    if plan is not None:
        session.update_results(plan, recipes, ratios, scored)

    for msg in state.get("messages") or []:
        role = msg.get("role")
        content = msg.get("content", "")
        if role == "user":
            session.add_user(content)
        elif role == "assistant":
            session.add_assistant(content)

    return session
